#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
README="${ROOT_DIR}/README.md"
RELEASE_DOC="${ROOT_DIR}/docs/release.md"
QUICKSTART_DOC="${ROOT_DIR}/docs/quickstart.md"
AGENT_SETUP_DOC="${ROOT_DIR}/docs/agent-setup.md"
TROUBLESHOOTING_DOC="${ROOT_DIR}/docs/troubleshooting.md"
BENCHMARKING_DOC="${ROOT_DIR}/docs/benchmarking.md"
STORAGE_DOC="${ROOT_DIR}/docs/storage.md"
MEMORY_DOC="${ROOT_DIR}/docs/memory.md"
FEEDBACK_DOC="${ROOT_DIR}/docs/feedback.md"
WORKSPACE_DOC="${ROOT_DIR}/docs/workspace.md"
SHARED_ARTIFACTS_DOC="${ROOT_DIR}/docs/shared-artifacts.md"
ARCHITECTURE_DOC="${ROOT_DIR}/docs/architecture.md"
COMPONENTS_DOC="${ROOT_DIR}/docs/components.md"
CONTRACTS_DOC="${ROOT_DIR}/docs/data-contracts.md"
COMPILER_DOC="${ROOT_DIR}/docs/context-compiler.md"
INTEGRATIONS_DOC="${ROOT_DIR}/docs/integrations.md"
SEMANTIC_DOC="${ROOT_DIR}/docs/semantic.md"
PRECISION_DOC="${ROOT_DIR}/docs/precision.md"
INSPECTOR_DOC="${ROOT_DIR}/docs/inspector.md"
AGENT_PREVIEW_DOC="${ROOT_DIR}/docs/agent-preview.md"
RETRIEVAL_HEALTH_DOC="${ROOT_DIR}/docs/retrieval-health.md"
GRAPH_DOC="${ROOT_DIR}/docs/graph.md"
POLICY_EMBEDDING_DOC="${ROOT_DIR}/docs/policy-embedding.md"
DEMO_DOC="${ROOT_DIR}/docs/demo.md"
PUBLIC_SUMMARY_DOC="${ROOT_DIR}/docs/public-project-summary.md"
DISTRIBUTION_DOC="${ROOT_DIR}/docs/distribution.md"
RELEASE_GOVERNANCE_DOC="${ROOT_DIR}/docs/release-governance.md"
RELEASE_CHECKLIST_DOC="${ROOT_DIR}/packaging/release/release-checklist.md"

fail() {
  echo "release docs check failed: $*" >&2
  exit 1
}

require_file() {
  [[ -f "$1" ]] || fail "missing $1"
}

require_text() {
  local file="$1"
  local text="$2"
  grep -F -- "$text" "$file" >/dev/null || fail "missing '${text}' in ${file#${ROOT_DIR}/}"
}

reject_text() {
  local file="$1"
  local text="$2"
  if grep -F -- "$text" "$file" >/dev/null; then
    fail "unsupported required path '${text}' in ${file#${ROOT_DIR}/}"
  fi
}

require_file "${README}"
require_file "${RELEASE_DOC}"
require_file "${QUICKSTART_DOC}"
require_file "${AGENT_SETUP_DOC}"
require_file "${TROUBLESHOOTING_DOC}"
require_file "${STORAGE_DOC}"
require_file "${MEMORY_DOC}"
require_file "${FEEDBACK_DOC}"
require_file "${WORKSPACE_DOC}"
require_file "${SHARED_ARTIFACTS_DOC}"
require_file "${ARCHITECTURE_DOC}"
require_file "${COMPONENTS_DOC}"
require_file "${CONTRACTS_DOC}"
require_file "${COMPILER_DOC}"
require_file "${INTEGRATIONS_DOC}"
require_file "${SEMANTIC_DOC}"
require_file "${PRECISION_DOC}"
require_file "${INSPECTOR_DOC}"
require_file "${AGENT_PREVIEW_DOC}"
require_file "${RETRIEVAL_HEALTH_DOC}"
require_file "${GRAPH_DOC}"
require_file "${POLICY_EMBEDDING_DOC}"
require_file "${DEMO_DOC}"
require_file "${PUBLIC_SUMMARY_DOC}"
require_file "${DISTRIBUTION_DOC}"
require_file "${RELEASE_GOVERNANCE_DOC}"
require_file "${RELEASE_CHECKLIST_DOC}"

for file in "${README}" "${RELEASE_DOC}"; do
  require_text "$file" "ctxpack --version"
  require_text "$file" "ctxpack --help"
  require_text "$file" "v1.1.0"
  require_text "$file" "sha256sums.txt"
done

require_text "${README}" "ctxpack-v1.1.0"
require_text "${README}" "shasum -a 256 -c sha256sums.txt"
require_text "${README}" "sha256sum -c sha256sums.txt"
require_text "${README}" "docs/quickstart.md"
require_text "${README}" "docs/release.md"
require_text "${README}" "docs/agent-setup.md"
require_text "${README}" "docs/storage.md"
require_text "${README}" "docs/memory.md"
require_text "${README}" "docs/feedback.md"
require_text "${README}" "docs/workspace.md"
require_text "${README}" "docs/shared-artifacts.md"
require_text "${README}" "docs/architecture.md"
require_text "${README}" "docs/components.md"
require_text "${README}" "docs/data-contracts.md"
require_text "${README}" "docs/context-compiler.md"
require_text "${README}" "docs/inspector.md"
require_text "${README}" "docs/agent-preview.md"
require_text "${README}" "docs/integrations.md"
require_text "${README}" "docs/retrieval-health.md"
require_text "${README}" "docs/graph.md"
require_text "${README}" "docs/policy-embedding.md"
require_text "${README}" "docs/demo.md"
require_text "${README}" "docs/public-project-summary.md"
require_text "${README}" "docs/distribution.md"
require_text "${README}" "docs/release-governance.md"
require_text "${README}" "docs/semantic.md"
require_text "${README}" "docs/precision.md"
require_text "${README}" "docs/troubleshooting.md"
require_text "${README}" "ctxpack init --repo"
require_text "${README}" "ctxpack setup-check --repo"
require_text "${README}" "ctxpack doctor"
require_text "${README}" "ctxpack prepare-task"
require_text "${README}" "ctxpack get-pack"
require_text "${README}" "ctxpack inspector export"
require_text "${README}" "ctxpack://workspace/status"
require_text "${README}" "ctxpack://workspace/shared-artifacts"

require_text "${QUICKSTART_DOC}" "ctxpack --version"
require_text "${QUICKSTART_DOC}" "ctxpack --help"
require_text "${QUICKSTART_DOC}" "ctxpack init --repo"
require_text "${QUICKSTART_DOC}" "ctxpack setup-check --repo"
require_text "${QUICKSTART_DOC}" "ctxpack doctor"
require_text "${QUICKSTART_DOC}" "release manifest"
require_text "${QUICKSTART_DOC}" "local .ctxpack storage compatibility"
require_text "${QUICKSTART_DOC}" "ctxpack prepare-task"
require_text "${QUICKSTART_DOC}" "ctxpack get-pack"
require_text "${QUICKSTART_DOC}" "explicit \`--repo\`"
require_text "${QUICKSTART_DOC}" "session-scoped"
require_text "${QUICKSTART_DOC}" "get_pack"

require_text "${AGENT_SETUP_DOC}" "Codex CLI"
require_text "${AGENT_SETUP_DOC}" "ctxpack doctor"
require_text "${AGENT_SETUP_DOC}" "Claude Code"
require_text "${AGENT_SETUP_DOC}" "Cursor"
require_text "${AGENT_SETUP_DOC}" "OpenCode"
require_text "${AGENT_SETUP_DOC}" "deterministic protocol proof"
require_text "${AGENT_SETUP_DOC}" "real-client proof"
require_text "${AGENT_SETUP_DOC}" "prepare_task"
require_text "${AGENT_SETUP_DOC}" "get_pack"
require_text "${AGENT_SETUP_DOC}" "does not claim machine-checkable Cursor"
require_text "${AGENT_SETUP_DOC}" "does not claim machine-checkable OpenCode"

require_text "${TROUBLESHOOTING_DOC}" "PATH"
require_text "${TROUBLESHOOTING_DOC}" "absolute"
require_text "${TROUBLESHOOTING_DOC}" "CTXPACK_HOME"
require_text "${TROUBLESHOOTING_DOC}" "wrong cwd"
require_text "${TROUBLESHOOTING_DOC}" "MCP startup"
require_text "${TROUBLESHOOTING_DOC}" "stdout"
require_text "${TROUBLESHOOTING_DOC}" "setup-check"
require_text "${TROUBLESHOOTING_DOC}" "ctxpack doctor"
require_text "${TROUBLESHOOTING_DOC}" "Stale Binary Or Upgrade Mismatch"
require_text "${TROUBLESHOOTING_DOC}" "release manifest"
require_text "${TROUBLESHOOTING_DOC}" "does not run real agent clients"
require_text "${TROUBLESHOOTING_DOC}" "uninstall"
require_text "${TROUBLESHOOTING_DOC}" "state cleanup"
require_text "${TROUBLESHOOTING_DOC}" "session-scoped"
require_text "${TROUBLESHOOTING_DOC}" "get_pack"

require_text "${RELEASE_DOC}" "scripts/release-package.sh"
require_text "${RELEASE_DOC}" "scripts/audit-release-artifact.sh"
require_text "${RELEASE_DOC}" "scripts/verify-release-archive.sh"
require_text "${RELEASE_DOC}" "scripts/release-gate.sh"
require_text "${RELEASE_DOC}" "scripts/check-release-docs.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-first-pack.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-storage.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-memory.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-feedback.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-workspace.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-shared-artifacts.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-inspector.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-retrieval-health.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-graph.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-policy-embedding.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-agent-preview.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-demo-artifacts.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-distribution-metadata.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-release-governance.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-semantic.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-precision.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-v23-eval.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-mcp-protocol.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-codex-mcp.sh"
require_text "${RELEASE_DOC}" "scripts/smoke-claude-mcp.sh"
require_text "${RELEASE_DOC}" "v2.3 eval"
require_text "${RELEASE_DOC}" "fixed corpus identity"
require_text "${RELEASE_DOC}" "feature-export privacy"
require_text "${RELEASE_DOC}" "learned-policy status"
require_text "${RELEASE_DOC}" "external corpus unavailable"
require_text "${RELEASE_DOC}" "RefactoringMiner"
require_text "${RELEASE_DOC}" "CTXPACK_BIN"
require_text "${RELEASE_DOC}" "CTXPACK_PROOF_DIR"
require_text "${RELEASE_DOC}" "CARGO_TARGET_DIR"
require_text "${RELEASE_DOC}" "CTXPACK_REQUIRE_REAL_CLIENT"
require_text "${RELEASE_DOC}" "CTXPACK_SKIP_REAL_CLIENT"
require_text "${RELEASE_DOC}" "CTXPACK_REAL_CLIENT_EVIDENCE_DIR"
require_text "${RELEASE_DOC}" "cargo test --workspace"
require_text "${RELEASE_DOC}" "ctxpack doctor"
require_text "${RELEASE_DOC}" "wrong cwd"
require_text "${RELEASE_DOC}" "does not publish"
require_text "${RELEASE_DOC}" "does not create tags"
require_text "${RELEASE_DOC}" "does not mutate global agent config"
require_text "${RELEASE_DOC}" "does not run user project tests"
require_text "${RELEASE_DOC}" "Cursor and OpenCode real-client proof is not claimed"
require_text "${RELEASE_DOC}" "manifest.json"
require_text "${RELEASE_DOC}" "audit.json"
require_text "${RELEASE_DOC}" "release manifest"
require_text "${RELEASE_DOC}" "source-free proof bundle"
require_text "${RELEASE_DOC}" "binary SHA-256"
require_text "${RELEASE_DOC}" "archive SHA-256"
require_text "${RELEASE_DOC}" "clean extraction verification"
require_text "${RELEASE_DOC}" "not a self-update implementation"
require_text "${RELEASE_DOC}" "signing and notarization gaps"
require_text "${RELEASE_DOC}" "ready/deferred/blocked"
require_text "${RELEASE_DOC}" "rollback"
require_text "${RELEASE_DOC}" "cargo install --git https://github.com/thromel/ctxpack --tag v1.1.0 ctxpack --locked"
require_text "${RELEASE_DOC}" "cargo install --path crates/ctxpack --locked"
require_text "${RELEASE_DOC}" "cargo build -p ctxpack --release --locked"
require_text "${RELEASE_DOC}" "crates.io"
require_text "${RELEASE_DOC}" "Homebrew"
require_text "${RELEASE_DOC}" "self-update"
require_text "${RELEASE_DOC}" "signed installers"
require_text "${RELEASE_DOC}" "cloud telemetry"
require_text "${RELEASE_DOC}" "global agent config"

require_text "${STORAGE_DOC}" "ctxpack storage init --repo"
require_text "${STORAGE_DOC}" "ctxpack storage status --repo"
require_text "${STORAGE_DOC}" "ctxpack index --repo"
require_text "${STORAGE_DOC}" "--store"
require_text "${STORAGE_DOC}" "--semantic"
require_text "${STORAGE_DOC}" "does not store raw file contents"
require_text "${STORAGE_DOC}" "scripts/smoke-storage.sh"
require_text "${STORAGE_DOC}" "scripts/smoke-semantic.sh"
require_text "${STORAGE_DOC}" "scripts/smoke-memory.sh"

require_text "${FEEDBACK_DOC}" "ctxpack eval feedback record --repo"
require_text "${FEEDBACK_DOC}" "ctxpack eval feedback list --repo"
require_text "${FEEDBACK_DOC}" "ctxpack eval feedback summary --repo"
require_text "${FEEDBACK_DOC}" "ctxpack eval policy report --repo"
require_text "${FEEDBACK_DOC}" "ctxpack eval policy tune --repo"
require_text "${FEEDBACK_DOC}" "ctxpack eval policy apply"
require_text "${FEEDBACK_DOC}" "ctxpack eval policy rollback --repo"
require_text "${FEEDBACK_DOC}" "ctxpack eval outcome compare --repo"
require_text "${FEEDBACK_DOC}" "source-free"
require_text "${FEEDBACK_DOC}" "does not store raw prompts"
require_text "${FEEDBACK_DOC}" "scripts/smoke-feedback.sh"

require_text "${WORKSPACE_DOC}" "ctxpack workspace init --repo"
require_text "${WORKSPACE_DOC}" "ctxpack workspace status --repo"
require_text "${WORKSPACE_DOC}" "ctxpack workspace prepare-task"
require_text "${WORKSPACE_DOC}" "ctxpack workspace get-pack"
require_text "${WORKSPACE_DOC}" "ctxpack workspace artifacts export"
require_text "${WORKSPACE_DOC}" "ctxpack workspace policy init"
require_text "${WORKSPACE_DOC}" ".ctxpack/workspace.json"
require_text "${WORKSPACE_DOC}" "source-free"
require_text "${WORKSPACE_DOC}" "sourceTextLogged: false"
require_text "${WORKSPACE_DOC}" "scripts/smoke-workspace.sh"
require_text "${WORKSPACE_DOC}" "WorkspaceContextPlan"
require_text "${WORKSPACE_DOC}" "WorkspaceContextPack"

require_text "${SHARED_ARTIFACTS_DOC}" "Shared Artifacts"
require_text "${SHARED_ARTIFACTS_DOC}" "ctxpack workspace artifacts export"
require_text "${SHARED_ARTIFACTS_DOC}" "ctxpack workspace artifacts inspect"
require_text "${SHARED_ARTIFACTS_DOC}" "ctxpack workspace artifacts import"
require_text "${SHARED_ARTIFACTS_DOC}" "ctxpack workspace policy init"
require_text "${SHARED_ARTIFACTS_DOC}" "ctxpack workspace policy status"
require_text "${SHARED_ARTIFACTS_DOC}" ".ctxpack/shared-artifacts.json"
require_text "${SHARED_ARTIFACTS_DOC}" ".ctxpack/imported-shared-artifacts.json"
require_text "${SHARED_ARTIFACTS_DOC}" "source-free"
require_text "${SHARED_ARTIFACTS_DOC}" "sourceTextLogged: false"
require_text "${SHARED_ARTIFACTS_DOC}" "scripts/smoke-shared-artifacts.sh"

require_text "${ARCHITECTURE_DOC}" "ctxpack Architecture"
require_text "${ARCHITECTURE_DOC}" "mermaid"
require_text "${ARCHITECTURE_DOC}" "Crate Map"
require_text "${ARCHITECTURE_DOC}" "Runtime Flow"
require_text "${ARCHITECTURE_DOC}" "Major Decisions"
require_text "${ARCHITECTURE_DOC}" "Safety Invariants"
require_text "${ARCHITECTURE_DOC}" "workspace foundation"
require_text "${ARCHITECTURE_DOC}" "inspector.md"
require_text "${ARCHITECTURE_DOC}" "retrieval-health.md"
require_text "${ARCHITECTURE_DOC}" "graph.md"

require_text "${CONTRACTS_DOC}" "PackInspectorView"
require_text "${CONTRACTS_DOC}" "AgentPreviewReport"
require_text "${CONTRACTS_DOC}" "sourceBearing: true"
require_text "${CONTRACTS_DOC}" "sourceTextLogged: false"

require_text "${INSPECTOR_DOC}" "Pack Inspector"
require_text "${INSPECTOR_DOC}" "ctxpack inspector export"
require_text "${INSPECTOR_DOC}" "PackInspectorView"
require_text "${INSPECTOR_DOC}" "static, read-only local inspector"
require_text "${INSPECTOR_DOC}" "bash scripts/smoke-inspector.sh"
require_text "${INSPECTOR_DOC}" "sourceTextLogged: false"
require_text "${INSPECTOR_DOC}" "does not store raw source text"

require_text "${AGENT_PREVIEW_DOC}" "ctxpack agent preview"
require_text "${AGENT_PREVIEW_DOC}" "Codex CLI"
require_text "${AGENT_PREVIEW_DOC}" "Claude Code"
require_text "${AGENT_PREVIEW_DOC}" "Cursor"
require_text "${AGENT_PREVIEW_DOC}" "OpenCode"
require_text "${AGENT_PREVIEW_DOC}" "generic MCP"
require_text "${AGENT_PREVIEW_DOC}" "AGENTS.md"
require_text "${AGENT_PREVIEW_DOC}" "native tools"
require_text "${AGENT_PREVIEW_DOC}" "source-free"
require_text "${AGENT_PREVIEW_DOC}" "bash scripts/smoke-agent-preview.sh"

require_text "${RETRIEVAL_HEALTH_DOC}" "Retrieval Health"
require_text "${RETRIEVAL_HEALTH_DOC}" "ctxpack eval health"
require_text "${RETRIEVAL_HEALTH_DOC}" "sourceTextLogged: false"
require_text "${RETRIEVAL_HEALTH_DOC}" "bash scripts/smoke-retrieval-health.sh"
require_text "${RETRIEVAL_HEALTH_DOC}" "does not include raw source text"

require_text "${GRAPH_DOC}" "Graph Neighborhoods"
require_text "${GRAPH_DOC}" "ctxpack graph neighborhood"
require_text "${GRAPH_DOC}" "sourceTextLogged: false"
require_text "${GRAPH_DOC}" "bash scripts/smoke-graph.sh"
require_text "${GRAPH_DOC}" "non-recursive by default"

require_text "${POLICY_EMBEDDING_DOC}" "ctxpack semantic status"
require_text "${POLICY_EMBEDDING_DOC}" "ctxpack eval policy experiments"
require_text "${POLICY_EMBEDDING_DOC}" "local_hash"
require_text "${POLICY_EMBEDDING_DOC}" "cloud embeddings"
require_text "${POLICY_EMBEDDING_DOC}" "cloud reranking"
require_text "${POLICY_EMBEDDING_DOC}" "sourceTextLogged: false"
require_text "${POLICY_EMBEDDING_DOC}" "bash scripts/smoke-policy-embedding.sh"

require_text "${DEMO_DOC}" "Public Demo Artifacts"
require_text "${DEMO_DOC}" "scripts/generate-demo-artifacts.sh"
require_text "${DEMO_DOC}" "scripts/smoke-demo-artifacts.sh"
require_text "${DEMO_DOC}" "source-free"
require_text "${DEMO_DOC}" "pack-inspector.json"
require_text "${DEMO_DOC}" "retrieval-health.json"
require_text "${DEMO_DOC}" "graph-neighborhood.json"
require_text "${DEMO_DOC}" "policy-embedding.json"
require_text "${DEMO_DOC}" "agent-preview.json"

require_text "${PUBLIC_SUMMARY_DOC}" "Current Capabilities"
require_text "${PUBLIC_SUMMARY_DOC}" "Accurate Non-claims"
require_text "${PUBLIC_SUMMARY_DOC}" "read-only"
require_text "${PUBLIC_SUMMARY_DOC}" "source-free"
require_text "${PUBLIC_SUMMARY_DOC}" "Codex"
require_text "${PUBLIC_SUMMARY_DOC}" "Claude Code"

require_text "${DISTRIBUTION_DOC}" "Distribution Metadata"
require_text "${DISTRIBUTION_DOC}" "packaging/homebrew/ctxpack.rb.template"
require_text "${DISTRIBUTION_DOC}" "packaging/crates/README.md"
require_text "${DISTRIBUTION_DOC}" "packaging/release/update-metadata.schema.json"
require_text "${DISTRIBUTION_DOC}" "scripts/verify-release-archive.sh"
require_text "${DISTRIBUTION_DOC}" "scripts/smoke-distribution-metadata.sh"
require_text "${DISTRIBUTION_DOC}" "not a self-update implementation"
require_text "${DISTRIBUTION_DOC}" "signing and notarization gaps"
require_text "${DISTRIBUTION_DOC}" "does not install binaries"

require_text "${RELEASE_GOVERNANCE_DOC}" "Release Governance"
require_text "${RELEASE_GOVERNANCE_DOC}" "deterministic protocol proof"
require_text "${RELEASE_GOVERNANCE_DOC}" "optional real-client proof"
require_text "${RELEASE_GOVERNANCE_DOC}" "scripts/release-candidate-status.sh"
require_text "${RELEASE_GOVERNANCE_DOC}" "scripts/release-candidate-rollback.sh"
require_text "${RELEASE_GOVERNANCE_DOC}" "scripts/smoke-release-governance.sh"
require_text "${RELEASE_GOVERNANCE_DOC}" "ready"
require_text "${RELEASE_GOVERNANCE_DOC}" "deferred"
require_text "${RELEASE_GOVERNANCE_DOC}" "blocked"
require_text "${RELEASE_GOVERNANCE_DOC}" "rollback"
require_text "${RELEASE_GOVERNANCE_DOC}" "Cursor"
require_text "${RELEASE_GOVERNANCE_DOC}" "OpenCode"

require_text "${RELEASE_CHECKLIST_DOC}" "ctxpack Release Checklist"
require_text "${RELEASE_CHECKLIST_DOC}" "deterministic protocol proof"
require_text "${RELEASE_CHECKLIST_DOC}" "optional real-client proof"
require_text "${RELEASE_CHECKLIST_DOC}" "ready"
require_text "${RELEASE_CHECKLIST_DOC}" "deferred"
require_text "${RELEASE_CHECKLIST_DOC}" "blocked"
require_text "${RELEASE_CHECKLIST_DOC}" "rollback"
require_text "${RELEASE_CHECKLIST_DOC}" "Cursor"
require_text "${RELEASE_CHECKLIST_DOC}" "OpenCode"
require_text "${ARCHITECTURE_DOC}" "components.md"
require_text "${ARCHITECTURE_DOC}" "data-contracts.md"
require_text "${ARCHITECTURE_DOC}" "context-compiler.md"
require_text "${ARCHITECTURE_DOC}" "integrations.md"

require_text "${COMPONENTS_DOC}" "Component Guide"
require_text "${COMPONENTS_DOC}" "ctxpack-core"
require_text "${COMPONENTS_DOC}" "ctxpack-index"
require_text "${COMPONENTS_DOC}" "ctxpack-compiler"
require_text "${COMPONENTS_DOC}" "ctxpack-mcp"
require_text "${COMPONENTS_DOC}" "Feature Placement Rule"

require_text "${CONTRACTS_DOC}" "Data Contracts"
require_text "${CONTRACTS_DOC}" "ContextPlan"
require_text "${CONTRACTS_DOC}" "ContextPack"
require_text "${CONTRACTS_DOC}" "WorkspaceInventoryReport"
require_text "${CONTRACTS_DOC}" "Source-Free Fields"

require_text "${COMPILER_DOC}" "Context Compiler"
require_text "${COMPILER_DOC}" "Retrieval Signals"
require_text "${COMPILER_DOC}" "Ranking And Budgeting"
require_text "${COMPILER_DOC}" "Workspace-Aware Planning"
require_text "${COMPILER_DOC}" "repoPacks"
require_text "${COMPILER_DOC}" "Trade-Offs"

require_text "${INTEGRATIONS_DOC}" "Agent Integrations"
require_text "${INTEGRATIONS_DOC}" "AGENTS.md"
require_text "${INTEGRATIONS_DOC}" "MCP"
require_text "${INTEGRATIONS_DOC}" "Native Rules"
require_text "${INTEGRATIONS_DOC}" "ctxpack://workspace/status"
require_text "${INTEGRATIONS_DOC}" "ctxpack://workspace/shared-artifacts"

require_text "${MEMORY_DOC}" "ctxpack cards generate --repo"
require_text "${MEMORY_DOC}" "ctxpack memory generate-experience --repo"
require_text "${MEMORY_DOC}" "ctxpack memory list --repo"
require_text "${MEMORY_DOC}" "ctxpack memory show"
require_text "${MEMORY_DOC}" "ctxpack memory regenerate"
require_text "${MEMORY_DOC}" "ctxpack memory approve"
require_text "${MEMORY_DOC}" "ctxpack memory reject"
require_text "${MEMORY_DOC}" "ctxpack memory disable"
require_text "${MEMORY_DOC}" "selectedMemory"
require_text "${MEMORY_DOC}" "ctxpack://repo/memory"
require_text "${MEMORY_DOC}" "source-free"
require_text "${MEMORY_DOC}" "does not store raw prompts"
require_text "${MEMORY_DOC}" "scripts/smoke-memory.sh"

require_text "${SEMANTIC_DOC}" "ctxpack search"
require_text "${SEMANTIC_DOC}" "--semantic"
require_text "${SEMANTIC_DOC}" "local_hash"
require_text "${SEMANTIC_DOC}" "ctxpack-local-hash-v1"
require_text "${SEMANTIC_DOC}" "MCP"
require_text "${SEMANTIC_DOC}" "cloud embedding"
require_text "${SEMANTIC_DOC}" "scripts/smoke-semantic.sh"
require_text "${SEMANTIC_DOC}" "does not store raw file contents"

require_text "${PRECISION_DOC}" "ctxpack precision import"
require_text "${PRECISION_DOC}" "Java"
require_text "${PRECISION_DOC}" "Kotlin"
require_text "${PRECISION_DOC}" "SCIP"
require_text "${PRECISION_DOC}" "LSP"
require_text "${PRECISION_DOC}" "source-free"
require_text "${PRECISION_DOC}" "does not store source snippets"

require_text "${BENCHMARKING_DOC}" "scripts/smoke-v23-eval.sh"
require_text "${BENCHMARKING_DOC}" "fixed corpus ID"
require_text "${BENCHMARKING_DOC}" "paired baseline verdicts"
require_text "${BENCHMARKING_DOC}" "feature-export privacy"
require_text "${BENCHMARKING_DOC}" "learned-policy status"
require_text "${BENCHMARKING_DOC}" "Useful context at lexical parity is not world-class lift"
require_text "${BENCHMARKING_DOC}" "external corpus unavailable"
require_text "${BENCHMARKING_DOC}" "RefactoringMiner"

reject_text "${README}" "brew install ctxpack"
reject_text "${README}" "cargo install ctxpack"
reject_text "${README}" "cargo run -p ctxpack -- init"
reject_text "${README}" "cargo run -p ctxpack -- serve-mcp"
reject_text "${README}" "self-update is required"
reject_text "${README}" "signed installers are required"
reject_text "${README}" "cloud telemetry is required"
reject_text "${README}" "global agent config mutation is required"
reject_text "${QUICKSTART_DOC}" "cargo run -p ctxpack -- init"
reject_text "${QUICKSTART_DOC}" "cargo run -p ctxpack -- serve-mcp"
reject_text "${AGENT_SETUP_DOC}" "Cursor real-client proof"
reject_text "${AGENT_SETUP_DOC}" "OpenCode real-client proof"
reject_text "${AGENT_SETUP_DOC}" "Cursor tool-call validation is verified"
reject_text "${AGENT_SETUP_DOC}" "OpenCode tool-call validation is verified"
reject_text "${RELEASE_DOC}" "brew install ctxpack"
reject_text "${RELEASE_DOC}" "cargo install ctxpack"
reject_text "${RELEASE_DOC}" "gh release create"
reject_text "${RELEASE_DOC}" "git tag v1.1.0"
reject_text "${RELEASE_DOC}" "uploads artifacts"
reject_text "${RELEASE_DOC}" "publishes the release"
reject_text "${RELEASE_DOC}" "requires Cursor real-client proof"
reject_text "${RELEASE_DOC}" "requires OpenCode real-client proof"
reject_text "${RELEASE_DOC}" "self-update is required"
reject_text "${RELEASE_DOC}" "signed installers are required"
reject_text "${RELEASE_DOC}" "cloud telemetry is required"
reject_text "${RELEASE_DOC}" "global agent config mutation is required"

echo "release docs are consistent"
